name: Test release action
on:
  push:
    tags:
    - v*

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMAGE: docker.io/${{ github.repository }}
    steps:
      - uses: actions/checkout@v3
      - name: Build changelog from PRs
        if: startsWith(github.ref, 'refs/tags/v')
        uses: mikepenz/release-changelog-builder-action@v2
        with:
          configuration: ".github/changelog-configuration.json"
          # PreReleases still get a changelog, but the next full release gets a diff since the last full release,
          # combining possible changelogs of all previous PreReleases in between.
          # PreReleases show a partial changelog since last PreRelease.
          ignorePreReleases: "${{ !contains(github.ref, '-rc') }}"
      - name: Read release message from tag commit
        id: tag_message
        if: startsWith(github.ref, 'refs/tags/v')
        run:
          - echo "::set-output name=message::$(git tag -n --format='%(contents:body)' ${{ github.ref }} | head -n-1)"
      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: ncipollo/release-action@v1
        with:
          body: "## Summary\n\n${{steps.tag_message.outputs.message}}\n## Changes\n\n${{steps.build_changelog.outputs.changelog}}"
          prerelease: "${{ contains(github.ref, '-rc') }}"
          # To get "x commits to master since this release"
          commit: master
          token: ${{ secrets.GITHUB_TOKEN }}
