on:
  workflow_dispatch: {}
  push:
    branches:
      - master
  schedule:
    - cron: '*/5 * * * *'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: find cause
        run: echo $GITHUB_EVENT_NAME
