on:
  workflow_dispatch: {}
  push:
    branches:
      - master
  schedule:
    - cron: '3 * * * *'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Run on manual trigger
        run: echo "manually triggered"
        if: ${{ github.event_name == 'workflow_dispatch' }}
      - name: Run on push
        run: echo "push triggered"
        if: ${{ github.event_name == 'push' }}
      - name: Run on schedule
        run: echo "push triggered"
        if: ${{ github.event_name == 'schedule' }}
